# Generated by Django 4.2.7 on 2023-12-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('social_media_url', models.TextField(blank=True, null=True, unique=True)),
                ('social_media_type', models.CharField(blank=True, choices=[('reels', 'Reels'), ('shorts', 'Shorts'), ('video', 'Video')], max_length=10, null=True)),
                ('media_public_url', models.TextField(blank=True, null=True)),
                ('media_name', models.CharField(blank=True, max_length=255, null=True)),
                ('intermediate_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('public_url_created', 'Public Url Created'), ('success', 'Success'), ('failed', 'Failed')], default='created', max_length=50)),
                ('error', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='social_media.category')),
                ('destination_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_contents', to='social_media.credentials')),
                ('source_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_contents', to='social_media.credentials')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
