version: "3.3"
services:
  backend:
    build: .
    env_file:
      - ./.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: bash -c "python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8000:8080"
  main_queue:
    build: .
    env_file:
      - ./.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: bash -c "celery -A core worker -l DEBUG --concurrency=3 -Q main_queue"
